# kaniko.yml
name: "Ohio University Kaniko builder"
description: "Build and push docker images using Kaniko"
branding:
  icon: anchor
  color: orange
inputs:
  path:
    description: Path to the build context
    required: false
    default: "."
  registry:
    description: "Docker registry where the image will be pushed"
    required: false
  username:
    description: "Username used for authentication to the Docker registry"
    required: false
  password:
    description: "Password used for authentication to the Docker registry"
    required: false
  image:
    description: "Image name. If specified the ais build config will be ignored."
    required: false
  image_list_file: 
    description: "A file containing a list of images to build.  If this is specified the image, tag, and path parameters will be ignored."
    required: false
  build_config:
    description: |
      Path to a ais build config file.
    required: false
    default: './ais-build.yaml'
  tag:
    description: "Image tag"
    required: false
  cache:
    description: "Enables build cache"
    required: false
  cache_ttl:
    description: "How long the cache should be considered valid"
    required: false
  cache_registry:
    description: "Docker registry meant to be used as cache"
    required: false
  cache_directory:
    description: "Filesystem path meant to be used as cache"
    required: false
  build_file:
    description: "Dockerfile filename"
    required: false
  strip_tag_prefix:
    description: "Prefix to be stripped from the tag"
    required: false
  extra_args:
    description: "Additional arguments to be passed to the kaniko executor"
    required: false
  skip_unchanged_digest:
    description: "Avoids pushing the image if the build generated the same digest"
    required: false
  tag_with_latest:
    description: "Tags the built image with additional latest tag"
    required: false
  target:
    description: Sets the target stage to build
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
