name: Pull request
on: pull_request

jobs:
  commitsar:
    runs-on: ubuntu-latest
    name: Verify commit messages
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run commitsar
        uses: docker://aevea/commitsar@sha256:af10c4acc6a9d7fd20c4e373a341229ba59d44610cf700c84173ff1f376ef07b
